### ISSUE TITLE
Typo in the installation instructions on https://pypi.python.org/pypi/djangocms-style/1.5

### ISSUE THREAD

**Issue by sebastianmanger** [divio/djangocms-style#15]
On the [installation instructions](https://pypi.python.org/pypi/djangocms-style/1.5), "djangocms_style" is missing a "t":
> * If using Django 1.7 add ``'djangocms_syle': 'djangocms_syle.migrations_django',``

should be
> * If using Django 1.7 add ``'djangocms_style': 'djangocms_style.migrations_django',``

It's correct on the readme on github. Thanks for this project!

**Comment by yakky** [comment]
Fixed, thanks for reporting
