### ISSUE TITLE
Move migration files from migrations_django to its original place

### ISSUE THREAD

**Issue by saeedsq** [divio/djangocms-style#16]
According to django 1.7 inclusion of migration module:
Please change
1) migrations_django to migrations
2) migrations to south_migrations

**Comment by armicron** [comment]
Need to wait for django-cms 3.1.
```when django CMS 3.1 will be released, migrations for Django 1.7 will be moved to the standard location and the south-style ones to south_migrations.```

**Comment by saeedsq** [comment]
Are you up to date?!!
django-cms 3.1.2 is already released available in pypi:
https://pypi.python.org/pypi/django-cms/3.1.2

& following apps already moved their migration modules:
cms, menus, filer, djangocms_text_ckeditor
