### ISSUE TITLE
additional_classes class order being destroyed by 'set(...)'.

### ISSUE THREAD

**Issue by FilippoIOVINE** [divio/djangocms-style#36]
Hi,
Working with Semantic-UI css framework I need to care about css class names order I set styling items.

For example:
additional classes = "sixteen, wide, column"

after passing thru line 221 / models.py (djangocms-style 2.0.1):
`self.additional_classes = ', '.join(set(additional_classes))`
(clearly to purge redundant class names)

become:
additional classes = 'column,wide,sixteen'
losing class order when rendered.

**Comment by FinalAngel** [comment]
Hello @FilippoIOVINE thank you for the report, would you be able to propose a PR fix for this?

**Comment by FilippoIOVINE** [comment]
Done!
