### ISSUE TITLE
Alternative to djangocms-style

### ISSUE THREAD

**Issue by jrief** [divio/djangocms-style#4]
Started as a fork of this project, https://github.com/jrief/djangocms-cascade , now is a mature framework to manage a subtree of the DOM inside DjangoCMS placeholders.

Currently it works with Bootstrap-3.1, but in theory any other CSS framework can be added.

Thanks for seeding this project and please feel free to comment on djangocms-cascade. I would be pleased to put it under the hood of divio.

Jacob

**Comment by mkoistinen** [comment]
Closing as non-issue
